/**
 * SRT / VTT → ASS 转换器。
 * libass(与 mpv 同源的渲染引擎)只认 ASS,统一转成 ASS 后交给 JASSUB 渲染,
 * 这样 SRT 字幕也能走同一条前端渲染管线,服务器端零参与。
 */

import type { EmbyApi } from '../api/emby'
import type { SubTrack } from '../pages/playerTypes'

export function subFormat(codec?: string): string {
  if (!codec) return 'srt'
  if (codec === 'subrip') return 'srt'
  return codec
}

/**
 * 抓取字幕原始文本。Emby 不同版本的字幕路由不一样
 * (有的带 StartPositionTicks 路径段,有的不带),依次尝试直到拿到有效文本。
 */
export async function fetchSubtitleText(
  api: EmbyApi,
  track: SubTrack,
  itemId: string,
  msId: string,
): Promise<string> {
  const fmt = subFormat(track.codec)
  const candidates = [
    track.deliveryUrl,
    `/emby/Videos/${itemId}/${msId}/Subtitles/${track.index}/Stream.${fmt}`,
    `/emby/Videos/${itemId}/${msId}/Subtitles/${track.index}/0/Stream.${fmt}`,
  ].filter((u): u is string => Boolean(u))

  let lastErr = '没有可用的字幕地址'
  for (const url of candidates) {
    try {
      const text = await api.fetchText(url)
      // 服务器出错时可能返回 HTML 错误页,当无效内容跳过
      if (text.trim() && !text.trimStart().startsWith('<')) return text
      lastErr = `${url}(返回空内容)`
    } catch (e) {
      lastErr = `${url} → ${e instanceof Error ? e.message : String(e)}`
    }
  }
  throw new Error(lastErr)
}

const ASS_HEADER = (resX: number, resY: number, fontname: string) => `[Script Info]
; Generated by emby-web-player
ScriptType: v4.00+
PlayResX: ${resX}
PlayResY: ${resY}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontname},${Math.round(resY / 14)},&H00FFFFFF,&H000000FF,&H00000000,&H96000000,0,0,0,0,100,100,0,0,1,${Math.round(resY / 300)},1,2,${Math.round(resY / 18)},${Math.round(resY / 18)},${Math.round(resY / 16)},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

const TS_RE = /(\d{1,2}):(\d{2}):(\d{2})[.,](\d{1,3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[.,](\d{1,3})/

function toAssTime(h: string, m: string, s: string, ms: string): string {
  const centis = String(Math.round(Number(ms.padEnd(3, '0').slice(0, 3)) / 10)).padStart(2, '0')
  return `${Number(h)}:${m}:${s}.${centis}`
}

function cleanLine(line: string): string {
  return line
    .replace(/<[^>]*>/g, '') // VTT 内联标签 <c> <i> 等
    .replace(/\{[^}]*\}/g, '') // SRT 花括号标签
    .trim()
}

export function textSubToAss(content: string, resX = 1280, resY = 720, fontname = ''): string {
  const lines = content.replace(/\r\n?/g, '\n').split('\n')
  const events: string[] = []
  let i = 0
  while (i < lines.length) {
    const m = lines[i].match(TS_RE)
    if (!m) {
      i++
      continue
    }
    const start = toAssTime(m[1], m[2], m[3], m[4])
    const end = toAssTime(m[5], m[6], m[7], m[8])
    i++
    // 时间轴下一行开始是字幕正文,直到空行
    const text: string[] = []
    while (i < lines.length && lines[i].trim() !== '') {
      text.push(cleanLine(lines[i]))
      i++
    }
    const body = text.filter(Boolean).join('\\N')
    if (body) events.push(`Dialogue: 0,${start},${end},Default,,0,0,0,,${body}`)
  }
  return ASS_HEADER(resX, resY, fontname) + events.join('\n') + '\n'
}

/**
 * 内容嗅探:优先看标记,再按格式特征。
 * 返回 'ass' | 'srt' | 'vtt' | 'ttml'
 */
export function sniffSubtitleFormat(text: string, contentType = ''): 'ass' | 'srt' | 'vtt' | 'ttml' {
  const head = text.trimStart().slice(0, 2000)
  if (head.startsWith('[Script Info]')) return 'ass'
  if (contentType.includes('vtt') || head.startsWith('WEBVTT')) return 'vtt'
  if (contentType.includes('ttml') || head.startsWith('<?xml') || head.startsWith('<tt')) return 'ttml'
  if (head.includes('subrip') || /^\d+\r?\n\d{2}:\d{2}:\d{2}[,.]/m.test(head)) return 'srt'
  return 'srt'
}

/** Dialogue 起始时间(秒),用于乱序修复 */
const ASS_TS = /Dialogue:[^,]*,(\d+):(\d{2}):(\d{2})[.,](\d{2})/

function assTsSeconds(line: string): number {
  const m = line.match(ASS_TS)
  if (!m) return Number.MAX_SAFE_INTEGER
  return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) + Number(m[4]) / 100
}

/**
 * ASS 归一化(uhdnow 同款思路):
 * 1. 强制 ScaledBorderAndShadow: yes(不同片源标签不一时描边/阴影比例一致)
 * 2. Dialogue 按起始时间排序(部分压制乱序,libass 不重排会闪烁跳行)
 * Style 字体名不动,交给 JASSUB 的 availableFonts/fallbackFont 链解析。
 */
export function normalizeAss(text: string): string {
  let out = text.replace(/\r\n?/g, '\n')
  out = out.replace(/ScaledBorderAndShadow\s*:\s*no\s*/gi, 'ScaledBorderAndShadow: yes')
  const lines = out.split('\n')
  const dialogueIdx = lines.map((l, i) => (l.startsWith('Dialogue:') ? i : -1)).filter((i) => i >= 0)
  if (dialogueIdx.length > 1) {
    const dialogueLines = dialogueIdx.map((i) => lines[i])
    dialogueLines.sort((a, b) => assTsSeconds(a) - assTsSeconds(b))
    dialogueIdx.forEach((idx, k) => (lines[idx] = dialogueLines[k]))
  }
  return lines.join('\n')
}

/**
 * 字幕文本 → libmedia/JASSUB 用的统一 ASS 文本。
 * ASS/SSA 原样归一化;SRT/VTT 转成 ASS;TTML 剥标签转 SRT 再转 ASS。
 */
const KANA_RE = /[\u3040-\u30FF\uFF66-\uFF9D]/

/** 从 Dialogue 行取正文(Format 前 9 个字段之后) */
function dialogueText(line: string): string {
  const parts = line.split(',')
  return parts.slice(9).join(',')
}

/** Dialogue 第 4 字段是样式名(Layer,Start,End,Style,...) */
function dialogueStyle(line: string): string {
  return (line.split(',')[3] ?? '').trim()
}

/** 样式名呈 JP/CN 成对时,判定为双语文件 */
function isJapaneseStyle(style: string, all: string[]): boolean {
  if (!/(^|[^a-z])jp([^a-z]|$)/i.test(style)) return false
  return all.some((x) => /(^|[^a-z])cn([^a-z]|$)/i.test(x))
}

function dialogueRange(line: string): [number, number] {
  const m = line.match(ASS_TS)
  if (!m) return [Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER]
  const t = assTsSeconds(line)
  // 无结束时间解析时给 4 秒默认跨度
  return [t, t + 4]
}

/**
 * 双语 ASS 拆分:字幕组常把日文原文和中译做成两条同时生效的 Dialogue,
 * libass 会上下分排,而 DOM 渲染器不做行碰撞避让 → 全叠在一起。
 * 规则:剔除"含假名 且 与任一纯中文 Dialogue 时间重叠"的日文行;
 * 纯日文字幕文件(所有行都含假名)不受影响。
 */
export function stripJapaneseEvents(ass: string): string {
  const lines = ass.split('\n')
  const dial = lines.filter((l) => l.startsWith('Dialogue:'))
  if (dial.length === 0) return ass
  const styles = dial.map((l) => dialogueStyle(l))
  const hasCn = dial.some((l) => !KANA_RE.test(dialogueText(l)))
  // 规则 1:样式名 JP/CN 成对 → 直接剔 JP 样式行(字幕组双语标准结构)
  const jpByStyle = dial.some((l, i) => isJapaneseStyle(styles[i], styles))
  // 规则 2:含假名 且 与纯中文 Dialogue 时间重叠 → 剔除
  const cnRanges = dial
    .filter((l) => !KANA_RE.test(dialogueText(l)))
    .map(dialogueRange)
  const keep = new Set<number>()
  dial.forEach((l, i) => keep.add(i))
  let removed = 0
  dial.forEach((l, i) => {
    const jpStyle = jpByStyle && isJapaneseStyle(styles[i], styles)
    if (!jpStyle && !KANA_RE.test(dialogueText(l))) return
    if (!jpStyle) {
      const [s, e] = dialogueRange(l)
      const overlaps = cnRanges.some(([cs, ce]) => s < ce && cs < e)
      if (!overlaps) return
    }
    keep.delete(i)
    removed++
  })
  if (removed === 0) return ass
  const out: string[] = []
  let di = 0
  for (const l of lines) {
    if (l.startsWith('Dialogue:')) {
      if (keep.has(di)) out.push(l)
      di++
    } else out.push(l)
  }
  return out.join('\n')
}

/** 双语剥离偏好(持久化在 localStorage,由播放器菜单切换) */
let stripBilingualEnabled = true

export function setBilingualStripPref(on: boolean): void {
  stripBilingualEnabled = on
}

export function getBilingualStripPref(): boolean {
  return stripBilingualEnabled
}

interface FixedEvent { start: number; end: number; lines: string[] }

function assTimeToSec(t: string): number {
  const m = t.match(/(\d+):(\d{2}):(\d{2})[.,](\d{1,3})/)
  if (!m) return NaN
  return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) + Number(m[4].padEnd(3, '0').slice(0, 3)) / 1000
}

function secToAssTime(t: number): string {
  const total = Math.max(0, t)
  const h = Math.floor(total / 3600)
  const m = Math.floor((total % 3600) / 60)
  const sec = Math.floor(total % 60)
  const cs = Math.round((total - Math.floor(total)) * 100)
  return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}.${String(cs).padStart(2, '0')}`
}

/** 任意格式 → 事件列表(秒 + 纯文本行,已去标签) */
function parseSubtitleEvents(raw: string, fmt: 'ass' | 'srt' | 'vtt' | 'ttml'): FixedEvent[] {
  const events: FixedEvent[] = []
  if (fmt === 'ass') {
    for (const line of raw.replace(/^\ufeff/, '').split('\n')) {
      if (!line.startsWith('Dialogue:')) continue
      // Dialogue: Layer, Start, End, Style, ..., Text(第 9 列起,可能含逗号)
      const parts = line.slice(9).split(',')
      const start = assTimeToSec(parts[1] ?? '')
      const end = assTimeToSec(parts[2] ?? '')
      const body = parts.slice(9).join(',').replace(/\{[^}]*\}/g, '').replace(/\\N/g, '\n')
      const lines = body.split('\n').map((x) => x.trim()).filter(Boolean)
      if (isFinite(start) && isFinite(end) && lines.length) events.push({ start, end, lines })
    }
    return events
  }
  // SRT / VTT
  const lines = raw.replace(/\r\n?/g, '\n').split('\n')
  let i = 0
  while (i < lines.length) {
    const m = lines[i].match(TS_RE)
    if (!m) { i++; continue }
    const start = assTimeToSec(`${m[1]}:${m[2]}:${m[3]}.${m[4]}`)
    const end = assTimeToSec(`${m[5]}:${m[6]}:${m[7]}.${m[8]}`)
    i++
    const body: string[] = []
    while (i < lines.length && lines[i].trim() !== '' && !TS_RE.test(lines[i])) {
      const t = cleanLine(lines[i])
      if (t) body.push(t)
      i++
    }
    if (isFinite(start) && isFinite(end) && body.length) events.push({ start, end, lines: body })
  }
  return events
}

/**
 * 固定格式字幕(用户可配置):所有文本字幕统一转换为
 * 单一样式(思源黑体)+ 底部居中 + 固定边距,不再跟随原字幕组排版。
 * 双语(日文+中文,无论分离事件还是同事件多行)同样固定在底部按行堆叠。
 * stripBilingual 开启时剥离日文行(持久化偏好)。
 */
export function toFixedFormatAss(
  raw: string,
  resX = 1920,
  resY = 1080,
  opts: { stripBilingual?: boolean } = {},
): string {
  const fmt = sniffSubtitleFormat(raw)
  let events = parseSubtitleEvents(raw, fmt)
  if (events.length === 0) return ''

  const strip = opts.stripBilingual ?? getBilingualStripPref()
  if (strip) {
    const isKana = (lines: string[]) => lines.some((l) => KANA_RE.test(l))
    const plain = events.filter((e) => !isKana(e.lines))
    // 行级:同一事件内,含假名的行且该事件还有非假名行 → 删假名行
    for (const e of events) {
      if (isKana(e.lines) && e.lines.some((l) => !KANA_RE.test(l))) {
        e.lines = e.lines.filter((l) => !KANA_RE.test(l))
      }
    }
    // 事件级:纯假名事件且与任一非假名事件时间重叠 → 删除
    events = events.filter((e) => {
      if (!isKana(e.lines)) return true
      return !plain.some((p) => e.start < p.end + 0.5 && p.start < e.end + 0.5)
    })
  }

  // 合并时间重叠的事件 → 固定位置按行堆叠(双语固定)
  events.sort((a, b) => a.start - b.start)
  const merged: FixedEvent[] = []
  for (const e of events) {
    const last = merged[merged.length - 1]
    if (last && e.start < last.end - 0.1) {
      last.end = Math.max(last.end, e.end)
      for (const l of e.lines) if (!last.lines.includes(l)) last.lines.push(l)
    } else {
      merged.push({ start: e.start, end: e.end, lines: [...e.lines] })
    }
  }

  const fs = Math.round(resY / 18)
  const header = `[Script Info]
; Generated by emby-web-player (fixed format)
ScriptType: v4.00+
PlayResX: ${resX}
PlayResY: ${resY}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,思源黑体,${Math.round(resY / 16)},&H00FFFFFF,&H000000FF,&H00000000,&H96000000,0,0,0,0,100,100,0,0,1,${Math.round(resY / 180)},1,2,${Math.round(resX / 14)},${Math.round(resX / 14)},${Math.round(resY / 18)},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`
  const body = merged
    .map((e) => `Dialogue: 0,${secToAssTime(e.start)},${secToAssTime(e.end)},Default,,0,0,0,,${e.lines.join('\\N')}`)
    .join('\n')
  return header + body + '\n'
}

export function toUnifiedAss(raw: string, resX: number, resY: number): string {
  const fmt = sniffSubtitleFormat(raw)
  if (fmt === 'ass') return normalizeAss(stripBilingualEnabled ? stripJapaneseEvents(raw) : raw)
  if (fmt === 'ttml') {
    const text = raw
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<[^>]*>/g, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
    return textSubToAss(text, resX, resY)
  }
  return textSubToAss(raw, resX, resY)
}

/** Dialogue 正文去掉 ASS 覆盖标签({\xxx}),保留换行 */
function stripAssTags(text: string): string {
  return text.replace(/\{[^}]*\}/g, '').replace(/\\N/g, '\n').trim()
}

/**
 * ASS → WebVTT(给原生 <video> 字幕轨用)。
 * 原生直连(mp4)路径不走 libass,转为 VTT 由浏览器渲染:
 * 样式/定位会丢失,但任何背景上都清晰可读。
 */
export function assToVtt(ass: string): string {
  const lines = ass.replace(/\r\n?/g, '\n').split('\n')
  const cueLines: string[] = ['WEBVTT', '']
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i]
    if (!l.startsWith('Dialogue:')) continue
    const parts = l.split(',')
    const start = parts[1]?.trim()
    const end = parts[2]?.trim()
    const text = stripAssTags(parts.slice(9).join(','))
    if (!start || !end || !text) continue
    const vttTime = (t: string) => {
      // ASS: H:MM:SS.cc → VTT: HH:MM:SS.mmm
      const m = t.match(/(\d+):(\d{2}):(\d{2})[.,](\d{1,3})/)
      if (!m) return null
      const [h, mi, sec, ms] = [m[1].padStart(2, '0'), m[2], m[3], m[4].padEnd(3, '0')]
      return `${h}:${mi}:${sec}.${ms}`
    }
    const vs = vttTime(start)
    const ve = vttTime(end)
    if (!vs || !ve) continue
    cueLines.push(`${vs} --> ${ve}`)
    for (const tl of text.split('\n')) cueLines.push(tl)
    cueLines.push('')
  }
  return cueLines.join('\n')
}


export interface SubCue {
  start: number
  end: number
  text: string
}

/** ASS → cue 列表(秒;文本已去标签;保留 \N 换行为 \n) */
export function parseAssCues(ass: string): SubCue[] {
  const cues: SubCue[] = []
  const lines = ass.replace(/\r\n?/g, '\n').split('\n')
  const ts = (t: string) => {
    const m = t.match(/(\d+):(\d{2}):(\d{2})[.,](\d{1,3})/)
    if (!m) return NaN
    return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) + Number(m[4].padEnd(3, '0').slice(0, 3)) / 1000
  }
  for (const l of lines) {
    if (!l.startsWith('Dialogue:')) continue
    const parts = l.split(',')
    const start = ts(parts[1] ?? '')
    const end = ts(parts[2] ?? '')
    const text = stripAssTags(parts.slice(9).join(','))
    if (!isFinite(start) || !isFinite(end) || !text) continue
    cues.push({ start, end, text })
  }
  return cues.sort((a, b) => a.start - b.start)
}

/** cue 列表 → SRT 文本(导出用) */
export function cuesToSrt(cues: SubCue[]): string {
  const fmt = (t: number) => {
    const total = Math.max(0, t)
    const h = Math.floor(total / 3600)
    const m = Math.floor((total % 3600) / 60)
    const s = Math.floor(total % 60)
    const ms = Math.round((total - Math.floor(total)) * 1000)
    return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(ms).padStart(3, '0')}`
  }
  return cues
    .map((c, i) => `${i + 1}\n${fmt(c.start)} --> ${fmt(c.end)}\n${c.text.replace(/\n/g, '\n')}\n`)
    .join('\n')
}
